### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by mauro3** [eth-vaw-glaciology/GlacioTools.jl#2]
@pohlan: can you enable GitHub Actions? To allow for CI to run?

Alternatively (or as well), you could transfer this repo to https://github.com/eth-vaw-glaciology and I can take care of it.

**Comment by pohlan** [comment]
Strange, there's nothing more I can enable in the CI part of the settings that isn't enabled already, or at least I cannot see anything.

For the transfer, it looks like I don't have the permission to do that. Maybe I need to be added to ETH-VAW Glaciology?

**Comment by mauro3** [comment]
Hmm, not sure either.  I made you member of eth-vaw-g...

**Comment by pohlan** [comment]
Now the transfer was successful, I hope the CI also works.

**Comment by mauro3** [comment]
Tnx!
